# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lars/fuerte_workspace/sandbox/URRealTime

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lars/fuerte_workspace/sandbox/URRealTime

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lars/fuerte_workspace/sandbox/URRealTime/CMakeFiles /home/lars/fuerte_workspace/sandbox/URRealTime/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lars/fuerte_workspace/sandbox/URRealTime/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_cpp

# Build rule for target.
ROSBUILD_genmsg_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_cpp
.PHONY : ROSBUILD_genmsg_cpp

# fast build rule for target.
ROSBUILD_genmsg_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_cpp.dir/build.make CMakeFiles/ROSBUILD_genmsg_cpp.dir/build
.PHONY : ROSBUILD_genmsg_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_lisp

# Build rule for target.
ROSBUILD_genmsg_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_lisp
.PHONY : ROSBUILD_genmsg_lisp

# fast build rule for target.
ROSBUILD_genmsg_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_lisp.dir/build.make CMakeFiles/ROSBUILD_genmsg_lisp.dir/build
.PHONY : ROSBUILD_genmsg_lisp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_cpp

# Build rule for target.
ROSBUILD_gensrv_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_cpp
.PHONY : ROSBUILD_gensrv_cpp

# fast build rule for target.
ROSBUILD_gensrv_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_cpp.dir/build.make CMakeFiles/ROSBUILD_gensrv_cpp.dir/build
.PHONY : ROSBUILD_gensrv_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_lisp

# Build rule for target.
ROSBUILD_gensrv_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_lisp
.PHONY : ROSBUILD_gensrv_lisp

# fast build rule for target.
ROSBUILD_gensrv_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_lisp.dir/build.make CMakeFiles/ROSBUILD_gensrv_lisp.dir/build
.PHONY : ROSBUILD_gensrv_lisp/fast

#=============================================================================
# Target rules for targets named clean-test-results

# Build rule for target.
clean-test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-test-results
.PHONY : clean-test-results

# fast build rule for target.
clean-test-results/fast:
	$(MAKE) -f CMakeFiles/clean-test-results.dir/build.make CMakeFiles/clean-test-results.dir/build
.PHONY : clean-test-results/fast

#=============================================================================
# Target rules for targets named rosbuild_precompile

# Build rule for target.
rosbuild_precompile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_precompile
.PHONY : rosbuild_precompile

# fast build rule for target.
rosbuild_precompile/fast:
	$(MAKE) -f CMakeFiles/rosbuild_precompile.dir/build.make CMakeFiles/rosbuild_precompile.dir/build
.PHONY : rosbuild_precompile/fast

#=============================================================================
# Target rules for targets named rosbuild_premsgsrvgen

# Build rule for target.
rosbuild_premsgsrvgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_premsgsrvgen
.PHONY : rosbuild_premsgsrvgen

# fast build rule for target.
rosbuild_premsgsrvgen/fast:
	$(MAKE) -f CMakeFiles/rosbuild_premsgsrvgen.dir/build.make CMakeFiles/rosbuild_premsgsrvgen.dir/build
.PHONY : rosbuild_premsgsrvgen/fast

#=============================================================================
# Target rules for targets named rospack_genmsg

# Build rule for target.
rospack_genmsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg
.PHONY : rospack_genmsg

# fast build rule for target.
rospack_genmsg/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg.dir/build.make CMakeFiles/rospack_genmsg.dir/build
.PHONY : rospack_genmsg/fast

#=============================================================================
# Target rules for targets named rospack_genmsg_libexe

# Build rule for target.
rospack_genmsg_libexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg_libexe
.PHONY : rospack_genmsg_libexe

# fast build rule for target.
rospack_genmsg_libexe/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg_libexe.dir/build.make CMakeFiles/rospack_genmsg_libexe.dir/build
.PHONY : rospack_genmsg_libexe/fast

#=============================================================================
# Target rules for targets named rospack_gensrv

# Build rule for target.
rospack_gensrv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_gensrv
.PHONY : rospack_gensrv

# fast build rule for target.
rospack_gensrv/fast:
	$(MAKE) -f CMakeFiles/rospack_gensrv.dir/build.make CMakeFiles/rospack_gensrv.dir/build
.PHONY : rospack_gensrv/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test-future

# Build rule for target.
test-future: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-future
.PHONY : test-future

# fast build rule for target.
test-future/fast:
	$(MAKE) -f CMakeFiles/test-future.dir/build.make CMakeFiles/test-future.dir/build
.PHONY : test-future/fast

#=============================================================================
# Target rules for targets named test-results

# Build rule for target.
test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results
.PHONY : test-results

# fast build rule for target.
test-results/fast:
	$(MAKE) -f CMakeFiles/test-results.dir/build.make CMakeFiles/test-results.dir/build
.PHONY : test-results/fast

#=============================================================================
# Target rules for targets named test-results-run

# Build rule for target.
test-results-run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results-run
.PHONY : test-results-run

# fast build rule for target.
test-results-run/fast:
	$(MAKE) -f CMakeFiles/test-results-run.dir/build.make CMakeFiles/test-results-run.dir/build
.PHONY : test-results-run/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named URRealTime

# Build rule for target.
URRealTime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URRealTime
.PHONY : URRealTime

# fast build rule for target.
URRealTime/fast:
	$(MAKE) -f src/CMakeFiles/URRealTime.dir/build.make src/CMakeFiles/URRealTime.dir/build
.PHONY : URRealTime/fast

#=============================================================================
# Target rules for targets named URRealTime-plugin

# Build rule for target.
URRealTime-plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URRealTime-plugin
.PHONY : URRealTime-plugin

# fast build rule for target.
URRealTime-plugin/fast:
	$(MAKE) -f src/CMakeFiles/URRealTime-plugin.dir/build.make src/CMakeFiles/URRealTime-plugin.dir/build
.PHONY : URRealTime-plugin/fast

#=============================================================================
# Target rules for targets named URRealTime-service

# Build rule for target.
URRealTime-service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URRealTime-service
.PHONY : URRealTime-service

# fast build rule for target.
URRealTime-service/fast:
	$(MAKE) -f src/CMakeFiles/URRealTime-service.dir/build.make src/CMakeFiles/URRealTime-service.dir/build
.PHONY : URRealTime-service/fast

#=============================================================================
# Target rules for targets named support

# Build rule for target.
support: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 support
.PHONY : support

# fast build rule for target.
support/fast:
	$(MAKE) -f src/CMakeFiles/support.dir/build.make src/CMakeFiles/support.dir/build
.PHONY : support/fast

#=============================================================================
# Target rules for targets named URRealTime-typekit-gnulinux

# Build rule for target.
URRealTime-typekit-gnulinux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URRealTime-typekit-gnulinux
.PHONY : URRealTime-typekit-gnulinux

# fast build rule for target.
URRealTime-typekit-gnulinux/fast:
	$(MAKE) -f typekit/CMakeFiles/URRealTime-typekit-gnulinux.dir/build.make typekit/CMakeFiles/URRealTime-typekit-gnulinux.dir/build
.PHONY : URRealTime-typekit-gnulinux/fast

#=============================================================================
# Target rules for targets named check-typekit-uptodate

# Build rule for target.
check-typekit-uptodate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-typekit-uptodate
.PHONY : check-typekit-uptodate

# fast build rule for target.
check-typekit-uptodate/fast:
	$(MAKE) -f typekit/CMakeFiles/check-typekit-uptodate.dir/build.make typekit/CMakeFiles/check-typekit-uptodate.dir/build
.PHONY : check-typekit-uptodate/fast

#=============================================================================
# Target rules for targets named regen

# Build rule for target.
regen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 regen
.PHONY : regen

# fast build rule for target.
regen/fast:
	$(MAKE) -f typekit/CMakeFiles/regen.dir/build.make typekit/CMakeFiles/regen.dir/build
.PHONY : regen/fast

#=============================================================================
# Target rules for targets named URRealTime-transport-corba-gnulinux

# Build rule for target.
URRealTime-transport-corba-gnulinux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URRealTime-transport-corba-gnulinux
.PHONY : URRealTime-transport-corba-gnulinux

# fast build rule for target.
URRealTime-transport-corba-gnulinux/fast:
	$(MAKE) -f typekit/transports/corba/CMakeFiles/URRealTime-transport-corba-gnulinux.dir/build.make typekit/transports/corba/CMakeFiles/URRealTime-transport-corba-gnulinux.dir/build
.PHONY : URRealTime-transport-corba-gnulinux/fast

#=============================================================================
# Target rules for targets named URRealTime-transport-mqueue-gnulinux

# Build rule for target.
URRealTime-transport-mqueue-gnulinux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URRealTime-transport-mqueue-gnulinux
.PHONY : URRealTime-transport-mqueue-gnulinux

# fast build rule for target.
URRealTime-transport-mqueue-gnulinux/fast:
	$(MAKE) -f typekit/transports/mqueue/CMakeFiles/URRealTime-transport-mqueue-gnulinux.dir/build.make typekit/transports/mqueue/CMakeFiles/URRealTime-transport-mqueue-gnulinux.dir/build
.PHONY : URRealTime-transport-mqueue-gnulinux/fast

#=============================================================================
# Target rules for targets named URRealTime-transport-typelib-gnulinux

# Build rule for target.
URRealTime-transport-typelib-gnulinux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URRealTime-transport-typelib-gnulinux
.PHONY : URRealTime-transport-typelib-gnulinux

# fast build rule for target.
URRealTime-transport-typelib-gnulinux/fast:
	$(MAKE) -f typekit/transports/typelib/CMakeFiles/URRealTime-transport-typelib-gnulinux.dir/build.make typekit/transports/typelib/CMakeFiles/URRealTime-transport-typelib-gnulinux.dir/build
.PHONY : URRealTime-transport-typelib-gnulinux/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ROSBUILD_genmsg_cpp"
	@echo "... ROSBUILD_genmsg_lisp"
	@echo "... ROSBUILD_gensrv_cpp"
	@echo "... ROSBUILD_gensrv_lisp"
	@echo "... clean-test-results"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... rosbuild_precompile"
	@echo "... rosbuild_premsgsrvgen"
	@echo "... rospack_genmsg"
	@echo "... rospack_genmsg_libexe"
	@echo "... rospack_gensrv"
	@echo "... test"
	@echo "... test-future"
	@echo "... test-results"
	@echo "... test-results-run"
	@echo "... tests"
	@echo "... uninstall"
	@echo "... URRealTime"
	@echo "... URRealTime-plugin"
	@echo "... URRealTime-service"
	@echo "... support"
	@echo "... URRealTime-typekit-gnulinux"
	@echo "... check-typekit-uptodate"
	@echo "... regen"
	@echo "... URRealTime-transport-corba-gnulinux"
	@echo "... URRealTime-transport-mqueue-gnulinux"
	@echo "... URRealTime-transport-typelib-gnulinux"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

